Move every CI env setup actions into a single composite custom action

diff --git a/.github/workflows/update-goldens.yml b/.github/workflows/update-goldens.yml
--- a/.github/workflows/update-goldens.yml
+++ b/.github/workflows/update-goldens.yml
@@ -7,7 +7,7 @@ name: Update Goldens
 on: workflow_dispatch
 
 jobs:
-    update_linux_goldens:
+    update_flutter_goldens:
         strategy:
             matrix:
                 os: [ubuntu-latest, macos-latest, windows-latest]
@@ -22,55 +22,47 @@ jobs:
                 shell: bash
 
         steps:
-            - name: Clone repository
-              uses: actions/checkout@v5
-              with:
-                  lfs: true
+          - name: Checkout code
+            uses: actions/checkout@v6
+            with:
+              # Fetch all commit metadata (build number is derived from number of commits)
+              fetch-depth: 0
+              # Don't download historical file contents (blobs)
+              filter: blob:none
 
-            - name: Set up Just
-              uses: extractions/setup-just@v2
+          - id: setup-buildenv
+            name: Setup build environment
+            uses: ./.github/actions/setup-buildenv
 
-            - name: Install FVM (Linux/macOS)
-              if: runner.os != 'Windows'
-              run: |
-                  just install-fvm
-                  echo $HOME/fvm/bin >> $GITHUB_PATH
+          - name: Update goldens
+            run: just update-flutter-goldens
 
-            - name: Install FVM (Windows)
-              if: runner.os == 'Windows'
-              run: choco install fvm
+          - name: Push changes
+            env:
+                BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
+            run: |
+                git config --local user.name 'github-actions[bot]'
+                git config --local user.email 'github-actions[bot]@users.noreply.github.com'
 
-            - run: cd app && fvm install
+                git fetch origin $BRANCH_NAME
+                git checkout $BRANCH_NAME
 
-            - name: Update goldens
-              run: just update-flutter-goldens
+                git add app/test
+                git commit -m "Update golden files" || echo "No changes to commit."
+                git status
+                git restore .
 
-            - name: Push changes
-              env:
-                  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
-              run: |
-                  git config --local user.name 'github-actions[bot]'
-                  git config --local user.email 'github-actions[bot]@users.noreply.github.com'
+                # Retry push if there are upstream changes
+                MAX_RETRIES=3
+                COUNT=0
 
-                  git fetch origin $BRANCH_NAME
-                  git checkout $BRANCH_NAME
-
-                  git add app/test
-                  git commit -m "Update golden files" || echo "No changes to commit."
-                  git status
-                  git restore .
-
-                  # Retry push if there are upstream changes
-                  MAX_RETRIES=3
-                  COUNT=0
-
-                  until git push; do
-                    COUNT=$((COUNT+1))
-                    if [ "$COUNT" -ge "$MAX_RETRIES" ]; then
-                      echo "Push failed after $MAX_RETRIES attempts."
-                      exit 1
-                    fi
-                    echo "Push failed, attempting to rebase and retry ($COUNT/$MAX_RETRIES)..."
-                    git fetch origin "$BRANCH_NAME"
-                    git rebase "origin/$BRANCH_NAME"
-                  done
+                until git push; do
+                  COUNT=$((COUNT+1))
+                  if [ "$COUNT" -ge "$MAX_RETRIES" ]; then
+                    echo "Push failed after $MAX_RETRIES attempts."
+                    exit 1
+                  fi
+                  echo "Push failed, attempting to rebase and retry ($COUNT/$MAX_RETRIES)..."
+                  git fetch origin "$BRANCH_NAME"
+                  git rebase "origin/$BRANCH_NAME"
+                done
